x-vault-common: &vault-common
  image: vault-alpine:1.0.1
  build:
    context: .
    args:
      VAULT_ENTERPRISE: true
  command: /entrypoint.sh
  # IPC_LOCK permite a Vault usar mlock y evitar que datos sensibles se escriban en swap.
  # No es obligatorio, pero recomendado en producción por seguridad.
  cap_add: ["IPC_LOCK"]
  environment:
    - VAULT_ADDR=http://127.0.0.1:8200
    - VAULT_LICENSE=${VAULT_LICENSE}
  labels:
    - vault-cluster

networks:
   vault_network:
    ipam:
      driver: default
      config:
        - subnet: 10.9.0.0/16
          ip_range: 10.9.0.0/16
          gateway: 10.9.0.1 

services:
  # --- Cluster A ---
  vaultA-transit:
    <<: *vault-common
    container_name: vaultA-transit
    volumes:
      - ./cluster-a/config/transit.hcl:/vault/config/vault.hcl:z
      - ./cluster-a/data/transit:/vault/data:z
      - ./cluster-a/run/transit/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.1.10

  vaultA-1:
    <<: *vault-common
    container_name: vaultA-1
    volumes:
      - ./cluster-a/config/node1.hcl:/vault/config/vault.hcl:z
      - ./cluster-a/data/node1:/vault/data:z
      - ./cluster-a/data/transit:/vault/token:z
      - ./cluster-a/run/node1/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.1.11  
    ports: ["8211:8200"]

  vaultA-2:
    <<: *vault-common
    container_name: vaultA-2
    volumes:
      - ./cluster-a/config/node2.hcl:/vault/config/vault.hcl:z
      - ./cluster-a/data/node2:/vault/data:z
      - ./cluster-a/data/transit:/vault/token:z
      - ./cluster-a/run/node2/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.1.12
    ports: ["8212:8200"]

  vaultA-3:
    <<: *vault-common
    container_name: vaultA-3
    volumes:
      - ./cluster-a/config/node3.hcl:/vault/config/vault.hcl:z
      - ./cluster-a/data/node3:/vault/data:z
      - ./cluster-a/data/transit:/vault/token:z
      - ./cluster-a/run/node3/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.1.13
    ports: ["8213:8200"]

  vaultA-agent:
    <<: *vault-common
    container_name: vaultA-agent
    command: "vault agent --config=/vault/config/vault.hcl"
    environment:
      - VAULT_ADDR=http://10.9.1.11:8200
      - VAULT_NAMESPACE=root
      - VAULT_LICENSE=${VAULT_LICENSE}
    volumes:
      - ./cluster-a/config/agent.hcl:/vault/config/vault.hcl:z
      - ./cluster-a/data/agent:/vault/data:z
      - ./cluster-a/data/transit:/vault/token:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.1.14

  # --- Cluster B ---
  vaultB-transit:
    <<: *vault-common
    container_name: vaultB-transit
    volumes:
      - ./cluster-b/config/transit.hcl:/vault/config/vault.hcl:z
      - ./cluster-b/data/transit:/vault/data:z
      - ./cluster-b/run/transit/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.2.10

  vaultB-1:
    <<: *vault-common
    container_name: vaultB-1
    volumes:
      - ./cluster-b/config/node1.hcl:/vault/config/vault.hcl:z
      - ./cluster-b/data/node1:/vault/data:z
      - ./cluster-b/data/transit:/vault/token:z
      - ./cluster-b/run/node1/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.2.11
    ports: ["8221:8200"]

  vaultB-2:
    <<: *vault-common
    container_name: vaultB-2
    volumes:
      - ./cluster-b/config/node2.hcl:/vault/config/vault.hcl:z
      - ./cluster-b/data/node2:/vault/data:z
      - ./cluster-b/data/transit:/vault/token:z
      - ./cluster-b/run/node2/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.2.12
    ports: ["8222:8200"]

  vaultB-3:
    <<: *vault-common
    container_name: vaultB-3
    volumes:
      - ./cluster-b/config/node3.hcl:/vault/config/vault.hcl:z
      - ./cluster-b/data/node3:/vault/data:z
      - ./cluster-b/data/transit:/vault/token:z
      - ./cluster-b/run/node3/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.2.13
    ports: ["8223:8200"]

  # --- Cluster C ---
  vaultC-transit:
    <<: *vault-common
    container_name: vaultC-transit
    volumes:
      - ./cluster-c/config/transit.hcl:/vault/config/vault.hcl:z
      - ./cluster-c/data/transit:/vault/data:z
      - ./cluster-c/run/transit/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.3.10

  vaultC-1:
    <<: *vault-common
    container_name: vaultC-1
    volumes:
      - ./cluster-c/config/node1.hcl:/vault/config/vault.hcl:z
      - ./cluster-c/data/node1:/vault/data:z
      - ./cluster-c/data/transit:/vault/token:z
      - ./cluster-c/run/node1/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.3.11
    ports: ["8231:8200"]

  vaultC-2:
    <<: *vault-common
    container_name: vaultC-2
    volumes:
      - ./cluster-c/config/node2.hcl:/vault/config/vault.hcl:z
      - ./cluster-c/data/node2:/vault/data:z
      - ./cluster-c/data/transit:/vault/token:z
      - ./cluster-c/run/node2/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.3.12
    ports: ["8232:8200"]

  vaultC-3:
    <<: *vault-common
    container_name: vaultC-3
    volumes:
      - ./cluster-c/config/node3.hcl:/vault/config/vault.hcl:z
      - ./cluster-c/data/node3:/vault/data:z
      - ./cluster-c/data/transit:/vault/token:z
      - ./cluster-c/run/node3/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.3.13
    ports: ["8233:8200"]

  # --- Cluster D ---
  vaultD-transit:
    <<: *vault-common
    container_name: vaultD-transit
    volumes:
      - ./cluster-d/config/transit.hcl:/vault/config/vault.hcl:z
      - ./cluster-d/data/transit:/vault/data:z
      - ./cluster-d/run/transit/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.4.10

  vaultD-1:
    <<: *vault-common
    container_name: vaultD-1
    volumes:
      - ./cluster-d/config/node1.hcl:/vault/config/vault.hcl:z
      - ./cluster-d/data/node1:/vault/data:z
      - ./cluster-d/data/transit:/vault/token:z
      - ./cluster-d/run/node1/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.4.11
    ports: ["8241:8200"]

  vaultD-2:
    <<: *vault-common
    container_name: vaultD-2
    volumes:
      - ./cluster-d/config/node2.hcl:/vault/config/vault.hcl:z
      - ./cluster-d/data/node2:/vault/data:z
      - ./cluster-d/data/transit:/vault/token:z
      - ./cluster-d/run/node2/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.4.12
    ports: ["8242:8200"]

  vaultD-3:
    <<: *vault-common
    container_name: vaultD-3
    volumes:
      - ./cluster-d/config/node3.hcl:/vault/config/vault.hcl:z
      - ./cluster-d/data/node3:/vault/data:z
      - ./cluster-d/data/transit:/vault/token:z
      - ./cluster-d/run/node3/entrypoint.sh:/entrypoint.sh:z
      - ./shared:/vault/shared:z
    networks: 
      vault_network:
        ipv4_address: 10.9.4.13
    ports: ["8243:8200"]
