x-vault-common: &vault-common
  image: vault-alpine:1.0.1
  build: .
  command: /entrypoint.sh
  # IPC_LOCK permite a Vault usar mlock y evitar que datos sensibles se escriban en swap.
  # No es obligatorio, pero recomendado en producción por seguridad.
  cap_add: ["IPC_LOCK"]
  environment:
    - VAULT_ADDR=http://127.0.0.1:8200
    - VAULT_LICENSE_PATH=/opt/vault/license
  labels:
    - vault-cluster

networks:
   vault_network:
    ipam:
      driver: default
      config:
        - subnet: 10.9.0.0/16
          ip_range: 10.9.0.0/16
          gateway: 10.9.0.1 

services:
  # --- Cluster A ---
  vaultA-transit:
    <<: *vault-common
    container_name: vaultA-transit
    volumes:
      - ./clusterA/config/transit.hcl:/vault/config/vault.hcl:z
      - ./clusterA/data/transit:/vault/data:z
      - ./run/entrypoint-transit.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.1.10

  vaultA-1:
    <<: *vault-common
    container_name: vaultA-1
    volumes:
      - ./clusterA/config/node1.hcl:/vault/config/vault.hcl:z
      - ./clusterA/data/node1:/vault/data:z
      - ./clusterA/data/transit:/vault/token:z
      - ./run/entrypoint-leader.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.1.11  
    ports: ["8211:8200"]

  vaultA-2:
    <<: *vault-common
    container_name: vaultA-2
    volumes:
      - ./clusterA/config/node2.hcl:/vault/config/vault.hcl:z
      - ./clusterA/data/node2:/vault/data:z
      - ./clusterA/data/transit:/vault/token:z
      - ./run/entrypoint.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.1.12
    ports: ["8212:8200"]

  vaultA-3:
    <<: *vault-common
    container_name: vaultA-3
    volumes:
      - ./clusterA/config/node3.hcl:/vault/config/vault.hcl:z
      - ./clusterA/data/node3:/vault/data:z
      - ./clusterA/data/transit:/vault/token:z
      - ./run/entrypoint.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.1.13
    ports: ["8213:8200"]

  # --- Cluster B ---
  vaultB-transit:
    <<: *vault-common
    container_name: vaultB-transit
    volumes:
      - ./clusterB/config/transit.hcl:/vault/config/vault.hcl:z
      - ./clusterB/data/transit:/vault/data:z
      - ./run/entrypoint-transit.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.2.10

  vaultB-1:
    <<: *vault-common
    container_name: vaultB-1
    volumes:
      - ./clusterB/config/node1.hcl:/vault/config/vault.hcl:z
      - ./clusterB/data/node1:/vault/data:z
      - ./clusterB/data/transit:/vault/token:z
      - ./run/entrypoint-leader.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.2.11
    ports: ["8221:8200"]

  vaultB-2:
    <<: *vault-common
    container_name: vaultB-2
    volumes:
      - ./clusterB/config/node2.hcl:/vault/config/vault.hcl:z
      - ./clusterB/data/node2:/vault/data:z
      - ./clusterB/data/transit:/vault/token:z
      - ./run/entrypoint.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.2.12
    ports: ["8222:8200"]

  vaultB-3:
    <<: *vault-common
    container_name: vaultB-3
    volumes:
      - ./clusterB/config/node3.hcl:/vault/config/vault.hcl:z
      - ./clusterB/data/node3:/vault/data:z
      - ./clusterB/data/transit:/vault/token:z
      - ./run/entrypoint.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.2.13
    ports: ["8223:8200"]

  # --- Cluster C ---
  vaultC-transit:
    <<: *vault-common
    container_name: vaultC-transit
    volumes:
      - ./clusterC/config/transit.hcl:/vault/config/vault.hcl:z
      - ./clusterC/data/transit:/vault/data:z
      - ./run/entrypoint-transit.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.3.10

  vaultC-1:
    <<: *vault-common
    container_name: vaultC-1
    volumes:
      - ./clusterC/config/node1.hcl:/vault/config/vault.hcl:z
      - ./clusterC/data/node1:/vault/data:z
      - ./clusterC/data/transit:/vault/token:z
      - ./run/entrypoint-leader.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.3.11
    ports: ["8231:8200"]

  vaultC-2:
    <<: *vault-common
    container_name: vaultC-2
    volumes:
      - ./clusterC/config/node2.hcl:/vault/config/vault.hcl:z
      - ./clusterC/data/node2:/vault/data:z
      - ./clusterC/data/transit:/vault/token:z
      - ./run/entrypoint.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.3.12
    ports: ["8232:8200"]

  vaultC-3:
    <<: *vault-common
    container_name: vaultC-3
    volumes:
      - ./clusterC/config/node3.hcl:/vault/config/vault.hcl:z
      - ./clusterC/data/node3:/vault/data:z
      - ./clusterC/data/transit:/vault/token:z
      - ./run/entrypoint.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.3.13
    ports: ["8233:8200"]

  # --- Cluster D ---
  vaultD-transit:
    <<: *vault-common
    container_name: vaultD-transit
    volumes:
      - ./clusterD/config/transit.hcl:/vault/config/vault.hcl:z
      - ./clusterD/data/transit:/vault/data:z
      - ./run/entrypoint-transit.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.4.10

  vaultD-1:
    <<: *vault-common
    container_name: vaultD-1
    volumes:
      - ./clusterD/config/node1.hcl:/vault/config/vault.hcl:z
      - ./clusterD/data/node1:/vault/data:z
      - ./clusterD/data/transit:/vault/token:z
      - ./run/entrypoint-leader.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.4.11
    ports: ["8241:8200"]

  vaultD-2:
    <<: *vault-common
    container_name: vaultD-2
    volumes:
      - ./clusterD/config/node2.hcl:/vault/config/vault.hcl:z
      - ./clusterD/data/node2:/vault/data:z
      - ./clusterD/data/transit:/vault/token:z
      - ./run/entrypoint.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.4.12
    ports: ["8242:8200"]

  vaultD-3:
    <<: *vault-common
    container_name: vaultD-3
    volumes:
      - ./clusterD/config/node3.hcl:/vault/config/vault.hcl:z
      - ./clusterD/data/node3:/vault/data:z
      - ./clusterD/data/transit:/vault/token:z
      - ./run/entrypoint.sh:/entrypoint.sh:z
      - ./license_vault.lic:/opt/vault/license:z
    networks: 
      vault_network:
        ipv4_address: 10.9.4.13
    ports: ["8243:8200"]
