x-vault-common: &vault-common
  image: vault-alpine
  build: .
  command: vault server -config=/vault/config/vault.hcl
  # IPC_LOCK permite a Vault usar mlock y evitar que datos sensibles se escriban en swap.
  # No es obligatorio, pero recomendado en producción por seguridad.
  cap_add: ["IPC_LOCK"]
  environment:
    - VAULT_ADDR=http://0.0.0.0:8200
  labels:
    - vault-cluster

networks:
  clusterA_net:
  clusterB_net:
  clusterC_net:
  clusterD_net:

services:
  # --- Cluster A ---
  vaultA-1:
    <<: *vault-common
    container_name: vaultA-1
    volumes:
      - ./clusterA/config/node1.hcl:/vault/config/vault.hcl:z
      - ./clusterA/data/node1:/vault/data:z
    networks: [clusterA_net]
    ports: ["8211:8200"]

  vaultA-2:
    <<: *vault-common
    container_name: vaultA-2
    volumes:
      - ./clusterA/config/node2.hcl:/vault/config/vault.hcl:z
      - ./clusterA/data/node2:/vault/data:z
    networks: [clusterA_net]
    ports: ["8212:8200"]

  vaultA-3:
    <<: *vault-common
    container_name: vaultA-3
    volumes:
      - ./clusterA/config/node3.hcl:/vault/config/vault.hcl:z
      - ./clusterA/data/node3:/vault/data:z
    networks: [clusterA_net]
    ports: ["8213:8200"]

  # --- Cluster B ---
  vaultB-1:
    <<: *vault-common
    container_name: vaultB-1
    volumes:
      - ./clusterB/config/node1.hcl:/vault/config/vault.hcl:z
      - ./clusterB/data/node1:/vault/data:z
    networks: [clusterB_net]
    ports: ["8221:8200"]

  vaultB-2:
    <<: *vault-common
    container_name: vaultB-2
    volumes:
      - ./clusterB/config/node2.hcl:/vault/config/vault.hcl:z
      - ./clusterB/data/node2:/vault/data:z
    networks: [clusterB_net]
    ports: ["8222:8200"]

  vaultB-3:
    <<: *vault-common
    container_name: vaultB-3
    volumes:
      - ./clusterB/config/node3.hcl:/vault/config/vault.hcl:z
      - ./clusterB/data/node3:/vault/data:z
    networks: [clusterB_net]
    ports: ["8223:8200"]

  # --- Cluster C ---
  vaultC-1:
    <<: *vault-common
    container_name: vaultC-1
    volumes:
      - ./clusterC/config/node1.hcl:/vault/config/vault.hcl:z
      - ./clusterC/data/node1:/vault/data:z
    networks: [clusterC_net]
    ports: ["8231:8200"]

  vaultC-2:
    <<: *vault-common
    container_name: vaultC-2
    volumes:
      - ./clusterC/config/node2.hcl:/vault/config/vault.hcl:z
      - ./clusterC/data/node2:/vault/data:z
    networks: [clusterC_net]
    ports: ["8232:8200"]

  vaultC-3:
    <<: *vault-common
    container_name: vaultC-3
    volumes:
      - ./clusterC/config/node3.hcl:/vault/config/vault.hcl:z
      - ./clusterC/data/node3:/vault/data:z
    networks: [clusterC_net]
    ports: ["8233:8200"]

  # --- Cluster D ---
  vaultD-1:
    <<: *vault-common
    container_name: vaultD-1
    volumes:
      - ./clusterD/config/node1.hcl:/vault/config/vault.hcl:z
      - ./clusterD/data/node1:/vault/data:z
    networks: [clusterD_net]
    ports: ["8241:8200"]

  vaultD-2:
    <<: *vault-common
    container_name: vaultD-2
    volumes:
      - ./clusterD/config/node2.hcl:/vault/config/vault.hcl:z
      - ./clusterD/data/node2:/vault/data:z
    networks: [clusterD_net]
    ports: ["8242:8200"]

  vaultD-3:
    <<: *vault-common
    container_name: vaultD-3
    volumes:
      - ./clusterD/config/node3.hcl:/vault/config/vault.hcl:z
      - ./clusterD/data/node3:/vault/data:z
    networks: [clusterD_net]
    ports: ["8243:8200"]
